"""Interaction tests for the standalone prototype, not production acceptance tests.
Runs with Playwright/Chromium. It renders the generated HTML directly; no network
or original-source file is required. Supply CHROMIUM_PATH for a local browser.
"""
from pathlib import Path
from playwright.sync_api import sync_playwright
import os,json,hashlib
ROOT=Path(__file__).parent
results=[]
def record(name,condition):
    if not condition: raise AssertionError(name)
    results.append({'test':name,'status':'PASS'})
with sync_playwright() as p:
    executable=os.environ.get('CHROMIUM_PATH','/usr/bin/chromium')
    args={'headless':True}
    if Path(executable).exists(): args.update(executable_path=executable,args=['--no-sandbox'])
    browser=p.chromium.launch(**args)
    page=browser.new_page(viewport={'width':1440,'height':1000},accept_downloads=True)
    errors=[];page.on('pageerror',lambda error:errors.append(str(error)))
    page.set_content((ROOT/'index.html').read_text(),wait_until='domcontentloaded')
    def ev(js): return page.evaluate(js)
    def role(r):page.locator('#role-select').select_option(r)
    def route(r):ev(f"go('{r}')")
    def reset():ev("state=seed();ui.selectedReview='RN-001';ui.reviewTab='notes';ui.accountTab='tb';render()")
    for r in ev('knownRoutes'):
        route(r)
        record('Route renders: '+r,page.locator('h1').count()==1)
        record('Desktop viewport: '+r,not ev('document.documentElement.scrollWidth>innerWidth'))
    for key,route_name,values in [('accountTab','accounting',['tb','mapping','adjustments','reconciliations','statements']),('auditTab','audit',['workpapers','risks','sampling','memoranda']),('reviewTab','reviews',['notes','approvals','history']),('requirementTab','requirements',['lifecycle','modes','architecture','source']),('onboardTab','onboarding',['assessment','questions','clearances'])]:
        for value in values:
            ev(f"ui.{key}='{value}';go('{route_name}')")
            record(f'Tab renders: {key}/{value}',page.locator('h1').count()==1)
    record('Original source sections preserved',ev('PRD.sections.length')==27)
    record('All lifecycle stages preserved',ev('PRD.lifecycle.length')==26)
    record('Primary and additional service categories',ev('PRD.services.length')==13)
    for text in ['', 'abc','AuditSphere — sample '+('x'*99)]:
        actual=page.evaluate('(text)=>sha256(text)',text)
        record('SHA-256 identity vector '+str(len(text)),actual==hashlib.sha256(text.encode()).hexdigest())
    reset();route('accounting')
    record('Original adjusted profit matches PRD',ev('totals().profit')==250000)
    record('Original adjusted assets match PRD',ev('totals().assets')==2250000)
    ev("actions['replace-tb']()")
    record('Replacement TB does not double-apply journal',ev('totals().profit')==250000)
    ev("actions['replace-tb']()")
    record('Repeated replacement is idempotent',ev('totals().profit')==250000 and ev('E().sourceVersion')==2)
    reset();route('reviews');role('reviewer')
    page.locator('#review-response').fill('A reviewer cannot submit their own preparer response.')
    page.locator('[data-action="respond-note"]').click()
    record('Wrong role cannot respond as preparer',ev('E().reviews[0].status')=='Open')
    for rid in ['RN-001','RN-002']:
        ev(f"ui.selectedReview='{rid}';ui.reviewTab='notes';go('reviews')")
        role('preparer')
        page.locator('#review-response').fill('Synthetic supporting evidence reviewed and correction explained for '+rid+'. Demonstration only.')
        page.locator('[data-action="respond-note"]').click()
        record('Preparer response: '+rid,ev(f"E().reviews.find(r=>r.id==='{rid}').status")=='Responded')
        page.locator('[data-action="clear-note"]').click()
        record('Self-clearance denied: '+rid,ev(f"E().reviews.find(r=>r.id==='{rid}').status")=='Responded')
        role('reviewer')
        page.locator('[data-action="clear-note"]').click()
        record('Independent clearance: '+rid,ev(f"E().reviews.find(r=>r.id==='{rid}').status")=='Cleared')
    record('Responses stale the previous package',ev('E().builtGeneration!==E().generation'))
    route('accounting');page.locator('[data-action="build-package"]').first.click()
    record('Rebuild binds current generation',ev('E().builtGeneration===E().generation'))
    ev("ui.reviewTab='approvals';go('reviews')")
    role('partner');page.locator('[data-action="package-approve"][data-key="partner"]').click()
    record('Partner cannot bypass manager and management',not ev("isCurrent('partner')"))
    for r in ['manager','client','partner']:
        role(r);page.locator(f'[data-action="package-approve"][data-key="{r}"]').click()
        record('Current package approval: '+r,ev(f"isCurrent('{r}')"))
    record('Required EQR remains release blocker',ev("releaseBlockers().includes('Required EQR is incomplete')"))
    role('eqr');page.locator('[data-action="package-approve"][data-key="eqr"]').click()
    record('All required demo gates cleared',ev('releaseBlockers().length')==0)
    route('delivery');role('partner');page.locator('[data-action="prepare-release"]').click();page.wait_for_timeout(100)
    record('Candidate prepared',ev('!!E().candidate'))
    page.locator('[data-action="issue-release"]').click()
    record('One immutable demo release identity',ev('E().releases.length')==1)
    page.locator('[data-action="issue-release"]').click()
    record('Retry does not duplicate release',ev('E().releases.length')==1)
    preserved=ev('E().releases[0].artifact');manifest=ev('E().releases[0].serialized');digest=ev('E().releases[0].hash')
    record('Release digest matches exact manifest',hashlib.sha256(manifest.encode()).hexdigest()==digest)
    page.locator('[data-action="demo-deliver"]').click();role('records');page.locator('[data-action="archive"]').click()
    record('Demo archive requires delivered package',ev('!!E().archive'))
    ev("actions['source-change']()")
    record('Changed input blocks release',ev('releaseBlockers().length')>0)
    record('Changed input makes approval stale',not ev("isCurrent('partner')"))
    record('Issued preview remains unchanged',ev('E().releases[0].artifact')==preserved)
    record('Issued financial results remain unchanged',ev('E().releases[0].totals.profit')==250000)
    reset();route('continuance');role('partner')
    page.locator('[data-action="roll-forward"]').click()
    record('Rollover blocked before continuance',ev('state.engagements.length')==4)
    for i in range(6):page.locator(f'[data-change="annual"][data-id="{i}"]').check()
    page.locator('[data-action="continue-client"]').click();page.locator('[data-action="roll-forward"]').click()
    record('Next-year draft created once',ev('state.engagements.length')==5)
    record('No old balances or approvals copied',ev("state.engagements.at(-1).rows.length===0 && Object.values(state.engagements.at(-1).approvals).every(x=>x===null)"))
    page.locator('[data-action="roll-forward"]').click()
    record('Duplicate rollover returns existing draft',ev('state.engagements.length')==5)
    reset();route('accounting')
    before=ev('JSON.stringify(E().rows)')
    ev("uploadTarget={eng:E().id,type:'tb'}")
    page.locator('#tb-picker').set_input_files({'name':'unbalanced.csv','mimeType':'text/csv','buffer':b'Code,Account,Type,Balance\n0001,Cash,asset,1.00\n'})
    page.wait_for_timeout(150)
    record('Unbalanced CSV rejected atomically',ev('JSON.stringify(E().rows)')==before)
    valid=b'Code,Account,Type,Balance\n0001,Cash,asset,12.00\n0002,Capital,equity,-12.00\n'
    page.locator('#tb-picker').set_input_files({'name':'valid.csv','mimeType':'text/csv','buffer':valid});page.wait_for_timeout(150)
    record('Balanced CSV imported with leading zeros',ev("E().rows[0].code==='0001' && E().rows.length===2"))
    record('Imported source needs mapping review',not ev('E().mappingApproved'))
    sourceversion=ev('E().sourceVersion')
    ev("uploadTarget={eng:E().id,type:'tb'}")
    page.locator('#tb-picker').set_input_files({'name':'renamed.csv','mimeType':'text/csv','buffer':valid});page.wait_for_timeout(100)
    record('Identical CSV avoids duplicate import',ev('E().sourceVersion')==sourceversion)
    reset();route('documents');ev("uploadTarget={eng:E().id,pbc:'PBC-03'}")
    content=b'Illustrative local evidence only.'
    page.locator('#document-picker').set_input_files({'name':'evidence.txt','mimeType':'text/plain','buffer':content});page.wait_for_timeout(150)
    record('Evidence upload preserves received vs accepted',ev("E().pbc[2].status==='Received'"))
    record('Evidence local digest is correct',ev('E().pbc[2].sha')==hashlib.sha256(content).hexdigest())
    record('File bytes are not persisted in state','Illustrative local evidence only.' not in ev('JSON.stringify(state)'))
    ev('closeModal()')
    role('reviewer');ev("pbcModal('PBC-03')");page.locator('[data-action="pbc-accept"]').click()
    record('Evidence needs separate reviewer acceptance',ev("E().pbc[2].status==='Accepted'"))
    reset();route('acquisition');page.locator('[data-action="new-lead"]').first.click()
    page.locator('#lead-name').fill('<img src=x onerror=alert(1)>')
    page.locator('#lead-contact').fill('Synthetic contact');page.locator('[data-action="save-lead"]').click()
    record('User-entered markup escaped',page.locator('img').count()==0)
    record('Inquiry creates local lead',ev('state.leads.length')==5)
    page.locator('[data-action="search"]').click();page.locator('#global-search').fill('Cedar')
    record('Global search finds scoped demo record',page.locator('#search-results').inner_text().find('Cedar Manufacturing')>=0)
    page.keyboard.press('Escape');record('Dialog closes with Escape',page.locator('[role="dialog"]').count()==0)
    reset();route('billing');role('manager');before=ev('JSON.stringify(E().rows)')
    page.locator('[data-action="invoice"][data-id="INV-26001"]').click();page.locator('#receipt-amount').fill('1000');page.locator('[data-action="invoice-receipt"]').click()
    record('Demo receipt affects only firm billing',ev('state.invoices[0].paid')==100000 and ev('JSON.stringify(E().rows)')==before)
    for width in [390,768,1024]:
        page.set_viewport_size({'width':width,'height':900})
        for r in ev('knownRoutes'):
            route(r);record(f'Responsive viewport {width}: {r}',not ev('document.documentElement.scrollWidth>innerWidth'))
    record('No browser runtime errors',not errors)
    browser.close()
report={'scope':'Prototype interaction and rendering checks, not production acceptance','renderer':'Chromium via Playwright; self-contained HTML injected into a local browser context','network':'No provider or application network requests','storage_note':'Opaque-origin rendering exercises in-memory fallback; real browser localStorage persistence is not proven by this test','passed':len(results),'failed':0,'results':results}
(ROOT/'test_results.json').write_text(json.dumps(report,indent=2))
print(json.dumps({'passed':len(results),'failed':0,'browser_errors':errors},indent=2))
