// Distilled from the 39 module rehearsal guides in modules/MOD-*.md (client-demo task pack).
// Static presenter/client guidance only — no second requirements or status database.
export interface ModuleGuideEntry {
  id: string; name: string; route: string; component: string; personas: string; scenario: string;
  exists: string; limits: string; steps: string[]; outcome: string; failure: string;
}

export const MODULE_GUIDES: ModuleGuideEntry[] = [
  {
    id: "MOD-01", name: "Practice Dashboard", route: "`overview`", component: "`DashboardView`",
    personas: "manager; repeat as partner, billing and a narrow-scope user", scenario: "`full-practice`",
    exists: "Scoped portfolio metrics, as-of/overdue filters and count-to-list checks already exist.", limits: "Remaining persona combinations, empty/archived states and exact drill-down continuity need demonstration evidence.",
    steps: [
      "Open Practice Overview as Layla Rahman. Set the demo as-of date to 2026-09-23.",
      "Filter by client and engagement; point out the selected context and currency.",
      "Open an overdue counter and compare its displayed total with the resulting list.",
      "Return and change assignee/as-of filters; explain why counts change.",
      "Switch to an eligible restricted persona and compare visibility, without treating a role switch as a real login.",
    ],
    outcome: "Every visible counter equals its scoped detail; a zero-work engagement does not imply complete readiness.",
    failure: "A completed overdue item must not be counted as open; a no-access context must not reveal hidden names or counts.",
  },
  {
    id: "MOD-02", name: "CRM & Client Management", route: "`clients → client-detail`", component: "`ClientsView / ClientDetailView`",
    personas: "relationship; manager for linked professional records", scenario: "`full-practice`",
    exists: "Client/contact creation, primary contact, custom values and non-authorizing relationship groups exist; contact responsibility/effective dates now have recorded implementation.", limits: "Complete lifecycle and stale-edit coverage, required-field reconciliation and all Client 360 actions remain open.",
    steps: [
      "Open Client Portfolio and select Example Trading Entity (CL-001).",
      "Review Profile and Contacts; identify the primary contact, relationship owner and client code.",
      "Create a distinct synthetic client/contact or edit a permitted field with a clear reason.",
      "Inspect a typed custom value and a relationship-group link; explain that neither grants access.",
      "Open a related engagement/invoice/document from Client 360 and return to the same client context.",
    ],
    outcome: "One shared client/contact identity appears across related screens; historical references survive inactivation/archive.",
    failure: "Try a duplicate normalized client code or invalid effective-date range; preserve the previous record after rejection.",
  },
  {
    id: "MOD-03", name: "Leads & Opportunities", route: "`acquisition`", component: "`LeadsPipelineView`",
    personas: "relationship", scenario: "`full-practice`",
    exists: "Inquiry editing, stage/loss history, currency-separated pipeline, Won conversion and permitted client linking are repository-reported verified.", limits: "Preserve the implementation; only include it in integrated presentation rehearsal and regression.",
    steps: [
      "Open Acquisition & Pipeline and select an inquiry.",
      "Review service interest, expected fee/currency and stage history.",
      "Qualify the inquiry; show how open pipeline totals change.",
      "Record Won and convert to a Prospect, or link a permitted existing client.",
      "Open the new client and point out that commercial conversion has not completed professional acceptance.",
    ],
    outcome: "One Prospect per conversion operation; no duplicate engagement, authority grant or professional approval is created.",
    failure: "A non-Won conversion must fail; Lost/Unqualified requires a reason and is excluded from open totals.",
  },
  {
    id: "MOD-04", name: "Proposals & Engagements", route: "`proposals → engagements`", component: "`ProposalsView / EngagementsView`",
    personas: "relationship → independent reviewer → client management → partner", scenario: "`full-practice`",
    exists: "Proposal drafting/review/presentation, evidence-backed client response, separate activation and engagement lifecycle editing exist.", limits: "Reusable content/service editor completeness, stale responses and full scope-change impact/rework need closure.",
    steps: [
      "Create a synthetic proposal from the selected opportunity/client; enter service, period, fee and terms.",
      "Submit, switch to a different eligible person and review the exact revision.",
      "Present it, switch to the permitted client management persona and record a manual response with evidence.",
      "Return to staff, create the linked draft engagement, then obtain a separate professional acceptance decision.",
      "Activate and review team/due dates; show suspend/resume or revise scope while retaining history.",
    ],
    outcome: "Commercial acceptance, professional acceptance and engagement activation remain separate attributable decisions.",
    failure: "Attempt same-person review and an old presented-revision response; do not bypass either guard.",
  },
  {
    id: "MOD-05", name: "Jobs & Tasks", route: "`jobs`", component: "`JobsTasksView`",
    personas: "manager → preparer / preparer-2", scenario: "`full-practice`",
    exists: "Jobs, one-level subtasks, reassignment, editing/reordering and task comments/document links are present; VP-014 is recorded verified despite a stale Requirements UI row.", limits: "Close job completion/nonterminal rework combinations; retain terminal cancellation and reconcile status text.",
    steps: [
      "Open Jobs & Tasks for the selected engagement; apply owner/status/overdue filters.",
      "Open a job and show linked files, time and its task hierarchy.",
      "Edit a task, reassign to Nadia Rahman with a reason and inspect history.",
      "Add an internal task note or link an already registered scoped document.",
      "Complete child work manually, then complete the parent/job only when required children are complete.",
    ],
    outcome: "Assignment, ordering, notes and status persist; assignment never grants professional approval authority.",
    failure: "An open child must block parent completion; a second nesting level and a cancelled-job reopen must be denied.",
  },
  {
    id: "MOD-06", name: "Job Templates", route: "`job-templates`", component: "`JobTemplatesView`",
    personas: "manager / permitted template author", scenario: "`full-practice`",
    exists: "Draft, publish, apply, revise and retire flows and repeat-operation safeguards are present.", limits: "Remaining title/hierarchy/selection/cancel matrices and role-suggestion interpretation need verification.",
    steps: [
      "Open Job Templates and inspect a published template.",
      "Create or edit a Draft with tasks and at most one child level.",
      "Publish it and manually create a job, deliberately choosing people and dates.",
      "Open the job and inspect its pinned template revision and fresh task states.",
      "Create a new template revision or retire the original; show that the previous job is unchanged.",
    ],
    outcome: "Templates copy structure only, never prior evidence, approvals, completed work or recurring schedules.",
    failure: "A Draft/Retired template cannot instantiate; a repeated operation creates one job, not two.",
  },
  {
    id: "MOD-07", name: "Team Collaboration", route: "`communications + jobs`", component: "`CommunicationsView / JobsTasksView`",
    personas: "preparer → permitted internal colleague", scenario: "`full-practice`",
    exists: "Authored notes/edits, staff mentions, recipient-local notices, read state and reasoned moderation now have recorded implementation.", limits: "Unsafe/oversized input, notification scope and subject-link consistency remain verify-first work.",
    steps: [
      "Open a job and add an internal note mentioning an eligible colleague.",
      "Switch to that colleague and inspect the local notice and linked record.",
      "Return as the author, edit the note and inspect attribution.",
      "Use permitted moderation only with a reason; preserve prior history.",
      "Switch to a client persona and show that internal notes, counts and references are absent.",
    ],
    outcome: "A local notice is not an email or chat service; edits and moderation retain attribution.",
    failure: "A client or ungranted staff member must not appear as an internal mention recipient.",
  },
  {
    id: "MOD-08", name: "Client Portal", route: "`portal`", component: "`ClientPortalView`",
    personas: "client_admin → client_finance → client", scenario: "`full-practice`",
    exists: "Scoped multi-client portal, issued invoice PDF downloads and separate management acknowledgements exist; sharing withdrawal has been implemented.", limits: "Rehearse every list/action and withdrawal/no-access branch across the three client roles.",
    steps: [
      "Choose Amal Nasser (client_admin) and open Client Experience Portal.",
      "Switch between her explicit CL-001 and CL-003 scopes; compare requests, documents and invoices.",
      "Choose Rami Nasser (client_finance) and demonstrate only his assigned contribution actions.",
      "Choose Omar Nasser (client management) and inspect the exact presented package before a decision.",
      "Download an issued demo invoice or a permitted generated artifact and explain its local/synthetic label.",
    ],
    outcome: "Contributing a file, administering client contacts and approving management content are different permissions.",
    failure: "No Pay button, internal workpaper, draft invoice, cost rate or ungranted CL-002 record is exposed.",
  },
  {
    id: "MOD-09", name: "Client Requests / PBC", route: "`client-detail Requests → portal`", component: "`ClientDetailView / ClientPortalView`",
    personas: "onboarding or permitted staff → named client_finance → independent staff reviewer", scenario: "`full-practice`",
    exists: "Draft/present/upload/clarify/replace/accept cycle and durable PBC blob/hash history are recorded working.", limits: "Request edit/reassign/cancel filters and the full accepted-response-to-evidence/procedure reassessment chain remain open.",
    steps: [
      "Open the selected client Requests tab and prepare a request with a due date and named contributor.",
      "Present it and show the simulated email preview; no message is sent.",
      "Switch to the named client contributor and upload a synthetic fixture to that request.",
      "Switch to a distinct eligible reviewer; ask for clarification or accept the exact response version.",
      "Request a reasoned replacement and inspect old response/acceptance history before re-review and evidence reassessment.",
    ],
    outcome: "PBC receipt is separate from adequacy and professional workpaper review; revisions are never silently substituted.",
    failure: "Uploader self-acceptance, wrong recipient, empty/unsupported file and quota failure must not create accepted metadata.",
  },
  {
    id: "MOD-10", name: "Document Management", route: "`documents`", component: "`DocumentsLibraryView`",
    personas: "manager / preparer with scoped access", scenario: "`full-practice`",
    exists: "Logical SharePoint hierarchy, metadata registration, revisions, availability, optional OneDrive and evidence replacement flows exist.", limits: "Complete idempotent workspace/rename/link matrices and truthful byte-availability explanations.",
    steps: [
      "Open Documents & SharePoint and select the client/engagement hierarchy.",
      "Inspect a logical document ID, current revision, sharing and source classification.",
      "Register a synthetic local file; distinguish metadata-only registration from a saved generated artifact or PBC blob.",
      "Replace a document revision and inspect old evidence pins and required reassessment.",
      "Rename/move or mark a reference unavailable, then restore it through the supported local control.",
    ],
    outcome: "SharePoint is a simulated canonical hierarchy, not a live transfer; each storage class states whether bytes survive reload.",
    failure: "Wrong roots, cross-scope evidence and unavailable originals must not open or become adequate evidence.",
  },
  {
    id: "MOD-11", name: "Communications", route: "`communications`", component: "`CommunicationsView`",
    personas: "relationship / permitted staff", scenario: "`full-practice`",
    exists: "Template-based simulated mail, accepted/failed/unknown outcomes and manual communication/job links exist.", limits: "Sender/placeholder/duplicate-click guards, visibility correction and all linked projections need final checks.",
    steps: [
      "Open Team & Client Comms and choose an existing active client contact.",
      "Compose from a permitted template and inspect resolved placeholders and attachment references.",
      "Explicitly simulate Accepted, Failed or Unknown and inspect the local attempt reference.",
      "Manually record a call/meeting or received-message note with visibility and optional job link.",
      "Open the same communication from Client 360/job activity and compare its identity/history.",
    ],
    outcome: "No provider receipt, real mail send, inbox sync, polling or automatic retry is implied.",
    failure: "Unresolved placeholders, out-of-client recipients and stale double-clicks must not claim delivery.",
  },
  {
    id: "MOD-12", name: "Time Tracking", route: "`my-time`", component: "`TimeTrackingView`",
    personas: "preparer → independent time reviewer", scenario: "`full-practice`",
    exists: "Draft/submit/return/approve and correction revisions already exist.", limits: "Remaining date/minute/link validation and already-billed correction impact need demonstrated closure.",
    steps: [
      "Open Time Tracking and enter positive minutes against a permitted job/task.",
      "Save Draft, submit and inspect the pending-review state.",
      "Switch to an independent reviewer, return with a reason or approve.",
      "Correct an approved record through a new revision rather than editing history.",
      "Open related budget/invoice views and explain approved versus unapproved and already-consumed time.",
    ],
    outcome: "Effective approved time drives totals; correction preserves the original approved rate and invoice history.",
    failure: "Self-approval, invalid minutes and a foreign job link are rejected; a correction must not become billable twice.",
  },
  {
    id: "MOD-13", name: "Budgets", route: "`budgets`", component: "`BudgetsView`",
    personas: "manager; preparer for related time entry", scenario: "`full-practice`",
    exists: "Revisioned budgets and approved-time rate snapshots exist.", limits: "Close fixed arithmetic, missing-cost and engagement/job aggregation cases and final variance UX.",
    steps: [
      "Open Budgets & Variances for the selected engagement/job.",
      "Set the dedicated rehearsal fixture to 600 planned minutes and QAR 200/hour billing rate.",
      "Provide 660 approved actual minutes and inspect +60 minutes and QAR 2,200 billable value.",
      "Enter QAR 80/hour cost for the fixture and inspect QAR 880 actual cost; remove it and show Unavailable.",
      "Revise the future budget rate and compare historical approved-time snapshots.",
    ],
    outcome: "Planned billing value is QAR 2,000; actual value/cost are separate, and no scheduling automation is introduced.",
    failure: "An absent cost rate must not display zero cost or fabricated margin; job and engagement totals must not double count.",
  },
  {
    id: "MOD-14", name: "Billing & Invoicing", route: "`billing`", component: "`BillingInvoicingView`",
    personas: "billing → independent billing reviewer", scenario: "`full-practice`",
    exists: "Approved-time/fixed-fee invoice sources, reservations, review/issue and partial credits exist.", limits: "Complete ad-hoc/draft/cancel/return, credit cap and download/correction matrices; reconcile whether per-service allocation is truly required.",
    steps: [
      "Open Billing & Invoices and select a client with approved billable time or an accepted proposal.",
      "Draft lines from permitted sources; compare currency, rate revision and remaining contract balance.",
      "Submit and obtain review from a different eligible person, then issue locally.",
      "Create and independently review a partial credit against the issued invoice.",
      "Open the client-safe invoice/download and receivables; explain local issue versus simulated mail versus settlement.",
    ],
    outcome: "Firm billing never changes the client TB or group books; invoicing stays a local demo record and no real payment request is used.",
    failure: "Duplicate time consumption, self-review, over-contract invoicing and excess credit must be blocked.",
  },
  {
    id: "MOD-15", name: "Receivables", route: "`receivables`", component: "`ReceivablesView`",
    personas: "billing", scenario: "`full-practice`",
    exists: "Offline receipts, split allocations, reversal history, as-of aging and bucket drill-down exist.", limits: "Complete all boundary/stale/currency/input matrices and browser print-content verification.",
    steps: [
      "Open Receivables & Receipts and set a client, currency and fixed as-of date.",
      "Inspect an issued invoice and effective credits before entering an offline receipt.",
      "Allocate part of a receipt across compatible invoices; inspect unallocated funds separately.",
      "Reverse one allocation with a reason and inspect both invoice and receipt history.",
      "Open an aging bucket, compare its invoice totals, export the statement and preview print.",
    ],
    outcome: "The dedicated QAR 1,000 invoice less 100 credit and 300 receipt gives QAR 600 in 31–60 days at 2026-09-23.",
    failure: "Future receipts do not reduce a past balance; cross-client/currency and over-allocation must fail atomically.",
  },
  {
    id: "MOD-16", name: "Reporting & Analytics", route: "`reports`", component: "`ReportingCentreView`",
    personas: "manager/partner; then billing and records", scenario: "`full-practice`",
    exists: "All 16 report views, field-level CSV reconciliation, role catalogues and invoked print actions are repository-reported verified.", limits: "Retain tests and rehearse client-friendly interpretation; no new BI integration is pending.",
    steps: [
      "Open Report Centre as manager and review the available report catalogue.",
      "Choose a practice report and filter by client/date/currency where offered.",
      "Open the linked source records and compare the displayed amounts/counts.",
      "Export CSV and preview print; explain approved time, WIP and invoicing definitions.",
      "Repeat as billing or records to show a smaller role-appropriate catalogue.",
    ],
    outcome: "Reports explain persisted synthetic records; they are not AI analytics, statutory accounts or a live BI connection.",
    failure: "A filtered export must not contain another client; missing rate-derived values remain unavailable.",
  },
  {
    id: "MOD-17", name: "Search & Centralized Client View", route: "`Shell search → exact record`", component: "`Shell / ClientDetailView`",
    personas: "manager; repeat as client_admin and a narrow-grant user", scenario: "`full-practice`",
    exists: "Deterministic text/metadata search, scoped filters and many exact-record targets exist.", limits: "Complete all persona/record/unavailable target permutations and return navigation.",
    steps: [
      "Open Search from the shell and enter a known synthetic client/job/task/document code.",
      "Filter result type and permitted client/engagement context.",
      "Open a result and verify both the record highlight and active engagement.",
      "Return to the previous list without losing filters or unsaved work.",
      "Repeat as Amal Nasser and demonstrate CL-001/CL-003 but not CL-002.",
    ],
    outcome: "Search selects the actual record rather than merely landing on a module home page; no semantic-search service is used.",
    failure: "Revoked, internal or unshared records must not leak via result text, counts or filter options.",
  },
  {
    id: "MOD-18", name: "Microsoft 365 Integration", route: "`m365-setup`", component: "`M365SetupView`",
    personas: "admin", scenario: "`full-practice`",
    exists: "Local setup, fixture people/role mapping, independent SharePoint/mail/optional OneDrive simulations and failures exist.", limits: "Complete start/back/cancel/summary, reconnect and stale-test matrices; improve clear local simulation instructions.",
    steps: [
      "Open Microsoft 365 Setup as system administrator and read the simulation banner.",
      "Enter/select only fixture tenant/site/library/root/sender values; review initial identity mappings.",
      "Run a simulated SharePoint check and a separate simulated mail check.",
      "Leave OneDrive disabled or explicitly enable it and demonstrate a bounded local metadata import.",
      "Disconnect or select a denied-site fixture, then show recovery and continued unrelated local jobs.",
    ],
    outcome: "Every success says Simulated; liveConnected remains false and scoped access grants are still separate.",
    failure: "No credentials, OAuth redirect or provider call is allowed; a failed optional mail test does not invalidate SharePoint.",
  },
  {
    id: "MOD-19", name: "Identity & Access Management", route: "`administration`", component: "`AdministrationView`",
    personas: "admin; test as the affected persona", scenario: "`full-practice`",
    exists: "Local identities/invite lifecycle are reported verified; scoped grant/effective-window/revocation paths exist.", limits: "Complete professional approval evidence, narrow-group and same-person expiry/revocation matrices.",
    steps: [
      "Open Firm Administration and inspect a synthetic person separately from client contacts.",
      "Nominate/create a local identity or show a simulated invitation state.",
      "Grant an explicitly approved client/engagement scope with reason and effective window.",
      "Switch to that persona and inspect permitted views.",
      "Revoke/expire the grant in the supported conflict test and show stale dialog removal and current denial.",
    ],
    outcome: "The browser illustrates intended authorization behavior; it is not a production authentication/security boundary.",
    failure: "A contact, role suggestion or system administrator label is not a professional approval or automatic scope grant.",
  },
  {
    id: "MOD-20", name: "Accounting", route: "`accounting-setup`", component: "`AccountingWorkbenchView`",
    personas: "permitted accounting preparer → independent reviewer", scenario: "`accounting-only`",
    exists: "Profiles, chart/period/book/dimension editors and independently reviewed versioned account mappings exist; mapping VP-037 is reported verified.", limits: "Finish wider setup edits and downstream stale/rework across same-client periods.",
    steps: [
      "Open Accounting Workbench for ENG-26002 and inspect client/entity, basis, currency, period and book.",
      "Review the posting chart and bounded dimension values.",
      "Create a valid profile/chart revision, retaining previous context.",
      "Map accepted TB accounts to statement lines and review independently.",
      "Change an affected chart/context and inspect stale mappings/statements/packages before reapproval.",
    ],
    outcome: "One client reporting context is preserved across imports and outputs; no operational ERP or new ledger is created.",
    failure: "Closed books, chart cycles, wrong-client references and invalid dimensions cannot silently alter approved output.",
  },
  {
    id: "MOD-21", name: "Trial Balance & GL", route: "`accounting-setup (TB and GL areas)`", component: "`AccountingWorkbenchView / import components`",
    personas: "preparer", scenario: "`accounting-only`",
    exists: "Genuine CSV/XLSX TB imports are reported verified; bounded mapped GL imports, immutable revisions and tie-out exist.", limits: "Complete remaining original-control, partial-batch/replacement, source-review and output-staleness paths.",
    steps: [
      "Open the TB import panel in Accounting Workbench; select the scoped chart/book.",
      "Import a genuine synthetic CSV/XLSX, map headers and inspect preview/control totals.",
      "Commit a valid source; compare accepted revision/hash with predecessor history.",
      "Import a GL source with explicit opening balances and column mapping.",
      "Inspect opening + movement = closing by account, journal drill-down and scoped export.",
    ],
    outcome: "Imported client sources are immutable; a successful preview is not a committed or professionally reviewed source.",
    failure: "Partial GL batches, missing openings and unbalanced or mislabeled workbooks remain incomplete/rejected without overwriting accepted data.",
  },
  {
    id: "MOD-22", name: "Adjustments & Journals", route: "`accounting-setup (adjustments) → portal approvals`", component: "`AccountingWorkbenchView / ClientPortalView`",
    personas: "preparer → independent technical reviewer → client management", scenario: "`accounting-only`",
    exists: "Balanced journals, separate technical/management review, reflection evidence and amendment history exist.", limits: "Complete rejected/reflected replacement-source and evidence/workpaper/finding linkage demonstrations.",
    steps: [
      "Draft a balanced reporting adjustment with a scoped evidence/workpaper/finding reference.",
      "Submit and obtain a different person’s technical review.",
      "Switch to authorized client management and record the separate decision.",
      "Set the evidence-backed reflection state against the exact TB source.",
      "Inspect statement impact, then amend or replace the source and show preserved history/reapproval.",
    ],
    outcome: "For the dedicated depreciation fixture assets move 23,000→22,500 and profit 3,000→2,500 once; no real ledger posting occurs.",
    failure: "Partial/Unknown reflection blocks relevant final output; an already-reflected adjustment must not be charged twice.",
  },
  {
    id: "MOD-23", name: "Reconciliations", route: "`accounting-setup (reconciliations)`", component: "`AccountingWorkbenchView`",
    personas: "preparer → independent reviewer", scenario: "`accounting-only`",
    exists: "Revisioned source-pinned schedules, typed timing/correction items, reasoned return and residual checks exist.", limits: "Close missing-evidence/correction-link and replacement-stale visibility cases, not live bank integration.",
    steps: [
      "Open a reconciliation schedule and select the exact scoped source/evidence revisions.",
      "Enter source balances and dated timing items separately from proposed corrections.",
      "Calculate and inspect the explained and unexplained residual.",
      "Submit to an independent reviewer, return with a reason, then create a rework revision.",
      "Replace an input and compare the stale current schedule with its retained approved predecessor.",
    ],
    outcome: "The source fixture $999,900 plus $100 timing reconciles to $1,000,000; keep currency labels explicit and do not mix it with QAR fixtures.",
    failure: "A nonzero unexplained residual, absent evidence or an unlinked proposed correction blocks approval.",
  },
  {
    id: "MOD-24", name: "Financial Statements", route: "`financial-statements`", component: "`FinancialStatementsView`",
    personas: "preparer → independent financial reviewer", scenario: "`accounting-only`",
    exists: "Mapped balance sheet/income statement, comparative history, reviewed cash-flow/equity schedules and shared notes exist.", limits: "Close bounded layout/grouping/subtotals, component-equity support where evidenced and full comparative/disclosure rework.",
    steps: [
      "Open Financial Statements with current approved mappings.",
      "Switch between statement types and trace a line to its source accounts.",
      "Select a compatible prior engagement; show Unavailable rather than fabricated zero when prior data is absent.",
      "Prepare/review evidence-backed cash-flow and equity movements, and select current note applicability.",
      "Save/review the exact statement revision, change an input and inspect stale state before regeneration.",
    ],
    outcome: "Statements reconcile to accepted sources and adjustments; synthetic methods/rates do not imply professional certification.",
    failure: "Unmapped comparatives, unsupported component equity and unreviewed notes/schedules must not appear as valid supported output.",
  },
  {
    id: "MOD-25", name: "Financial Packages", route: "`financial-packages`", component: "`FinancialPackagesView`",
    personas: "preparer → independent reviewer → client management", scenario: "`accounting-only`",
    exists: "Ordered sections, exact persisted XLSX/DOCX/PDF files, cash/equity inclusion, atomic failure cleanup and replacement acknowledgement exist.", limits: "Complete remaining sharing/generator-edge acceptance and make readiness/bytes guidance clear; do not rebuild exports.",
    steps: [
      "Open Financial Packages and select the exact current reviewed statement/schedule/note inputs.",
      "Choose and order supported sections, preview the client-visible contents.",
      "Assemble and inspect artifact identities, format, size and hashes.",
      "Download genuine watermarked XLSX/DOCX/PDF; independently review/present the exact revision.",
      "Amend a source/package and show fresh management acknowledgement with the predecessor preserved.",
    ],
    outcome: "The artifact bytes and hashes are browser-local persisted demo evidence, not externally delivered reports.",
    failure: "Internal-only note/comment/workpaper content must not appear in client artifacts; partial generation cannot announce a saved package.",
  },
  {
    id: "MOD-26", name: "Consolidation", route: "`consolidation`", component: "`ConsolidationView`",
    personas: "manager/group preparer → independent reviewer/partner", scenario: "`two-component-consolidation`",
    exists: "Supported perimeter, dated FX, manual elimination lifecycle and reviewed digest-bound JSON group artifacts exist.", limits: "Finish exact component replacement, duplicate/mixed-source elimination and full group output/rework acceptance.",
    steps: [
      "Load the Two-Component Group Consolidation preset and open GRP-01.",
      "Show the one Parent + one 100%-owned Subsidiary limitation and exact pinned component sources.",
      "Review a dated rate and account-level original/translated/rounding detail.",
      "Draft/submit a balanced manual elimination and obtain independent return/amend/approval.",
      "Prepare/review/download the supported group JSON artifact, then change an input to show stale blocking.",
    ],
    outcome: "Group totals equal supported component values plus approved eliminations; component TBs are unchanged. JSON is not advertised as a group XLSX/PDF.",
    failure: "Associate/minority profiles and missing rates are rejected; unmatched differences stay visible without a plug.",
  },
  {
    id: "MOD-27", name: "Client Acceptance", route: "`onboarding`", component: "`AuditAcceptanceView`",
    personas: "onboarding/compliance → separately assigned partner", scenario: "`full-practice`",
    exists: "Evidence-backed screening, prohibited outcome denial, independent acceptance and fresh continuance are reported verified.", limits: "Preserve it and include the commercial/professional decision distinction in the integrated client presentation.",
    steps: [
      "Open Acceptance & KYC for the synthetic prospect/client.",
      "Review screening questions and record each required manual evidence reference.",
      "Show the recommendation/pending state without auto-acceptance.",
      "Switch to the assigned partner and record the separate professional decision.",
      "Start an explicit next-period continuance and show new empty work records rather than copied approval/evidence.",
    ],
    outcome: "This is synthetic evidence recording, not a live KYC/AML screening service or professional certification.",
    failure: "A prohibited mandate or missing evidence cannot be accepted; repeating continuance creates only one linked draft.",
  },
  {
    id: "MOD-28", name: "Audit Planning", route: "`audit-planning`", component: "`AuditPlanningView`",
    personas: "preparer/manager → independent reviewer", scenario: "`full-practice`",
    exists: "A versioned planning screen, materiality helper, team/milestone tabs and independent review are present.", limits: "Replace contractual hard-coded assumptions with deliberate inputs; remove prefilled approval claims and correct misleading return feedback.",
    steps: [
      "Open Audit Planning & Materiality and inspect the selected engagement/source.",
      "Enter the synthetic benchmark, overall percentage, separate performance/trivial assumptions and rationale after the pending control is completed.",
      "Select eligible people and explicit dates; do not accept prefilled Completed milestones as evidence.",
      "Save a new Under review revision and switch to a different authorized reviewer.",
      "Return with a reason or approve; change an assumption and show dependent fieldwork reassessment.",
    ],
    outcome: "Calculations illustrate chosen assumptions. Any yet-unimplemented input control is a pending step, not a currently clickable feature.",
    failure: "No source benchmark or zero/invalid inputs must not silently fall back to invented data; Return must not report “gate cleared”.",
  },
  {
    id: "MOD-29", name: "Risks & Audit Programs", route: "`audit-risks`", component: "`AuditRisksProgramsView`",
    personas: "preparer/manager → independent reviewer", scenario: "`audit-findings`",
    exists: "Risk edits, reciprocal procedure links, reusable template revisions/application/retirement and plan return/rework exist.", limits: "Complete multi-risk change/reopen combinations and repeated reassessment evidence.",
    steps: [
      "Open Risks & Audit Programs and inspect one scoped risk and its response.",
      "Follow the reciprocal risk↔procedure links and coverage gaps.",
      "Draft/publish a supported program template, then apply it manually with fresh procedure IDs.",
      "Revise/retire a template without changing the already-applied engagement snapshot.",
      "Change a risk and show the new Under review plan, affected procedures and independent reassessment.",
    ],
    outcome: "Reusable audit programs are manual bounded templates, not a methodology/rules engine.",
    failure: "Cross-engagement links, Draft template application and unresolved reassessment block the related transition.",
  },
  {
    id: "MOD-30", name: "Audit Fieldwork", route: "`audit-risks / audit-fieldwork`", component: "`AuditRisksProgramsView`",
    personas: "preparer → assigned independent reviewer", scenario: "`audit-findings`",
    exists: "Procedure execution, current evidence/limitation checks and independent clearance exist.", limits: "Complete full exception/return/rework coverage and link to the existing VP-049 template owner.",
    steps: [
      "Open an engagement procedure (for example PRC-01) in Risks & Audit Programs.",
      "Read objective/instructions, linked risks and current evidence.",
      "Record work performed, results, exceptions or an explicit limitation.",
      "Submit the exact current revision and switch to its eligible independent reviewer.",
      "Return/rework/clear appropriately; compare an unresolved exception such as PRC-04 without hiding it.",
    ],
    outcome: "Submitting is not clearance; every applicable procedure retains its own work/result/reviewer state.",
    failure: "Preparer self-clearance, stale/inadequate evidence or reassessment-required procedures must not pass.",
  },
  {
    id: "MOD-31", name: "Populations & Sampling", route: "`sampling`", component: "`SamplingView`",
    personas: "preparer → independent selection reviewer", scenario: "`audit-findings`",
    exists: "Scoped population CSV/XLSX intake, manual selections/tests, finding links and independent evaluation are reported verified.", limits: "No new sampling engine required; demonstrate the existing local/manual scope and preserve regression.",
    steps: [
      "Open Sampling & Populations and choose POP-01 or a scoped synthetic import.",
      "Compare source period/currency and population-to-GL reconciliation.",
      "Record manual selection rationale and selected stable item IDs.",
      "Record tested, limited and untested outcomes and link an exception to a same-engagement finding.",
      "Obtain independent evaluation, then replace the population to demonstrate retained prior tests and required fresh selection.",
    ],
    outcome: "Counts and exceptions reconcile; the prototype does not infer statistical assurance or an audit conclusion.",
    failure: "Wrong period/currency, duplicate references or unresolved GL variance block selection/testing.",
  },
  {
    id: "MOD-32", name: "Workpapers", route: "`audit`", component: "`WorkpapersView`",
    personas: "preparer → assigned reviewer", scenario: "`audit-findings`",
    exists: "Template-pinned creation, genuine workbook versioning, evidence pinning, reassignment and independent clearance are reported verified.", limits: "Preserve the workspace and include its usage in the module tour; no duplicate workpaper subsystem.",
    steps: [
      "Open Audit Workpapers and choose/create the Cash & Bank workpaper from the supported template.",
      "Read the template version, purpose/guidelines and originating procedures.",
      "Save work and link exact current adequate evidence; inspect workbook availability.",
      "Submit the exact workpaper/workbook revision and switch to the assigned reviewer.",
      "Return or clear; demonstrate reasoned reassignment to a different eligible reviewer and retained history.",
    ],
    outcome: "Template provenance, preparation, submission and clearance are visibly separate and persist as documented for that storage class.",
    failure: "The same natural person cannot clear their own preparation; unavailable or stale supporting evidence remains explicit.",
  },
  {
    id: "MOD-33", name: "Evidence", route: "`evidence`", component: "`EvidenceCatalogueView`",
    personas: "preparer → independent adequacy reviewer", scenario: "`audit-findings`",
    exists: "Versioned adequacy, procedure/workpaper links, replacement reassessment and post-release preservation are reported verified.", limits: "Retain the existing flow; rehearse it alongside PBC and fieldwork without equating receipt with adequacy.",
    steps: [
      "Open Evidence Catalogue and inspect a document revision and adequacy state.",
      "Review its exact source/provenance and permitted engagement scope.",
      "Link adequate current evidence to a procedure/workpaper.",
      "Replace or unlink with a reason and inspect stale dependent work and retained old pins.",
      "Compare an already-issued release manifest to confirm its historical hashes remain unchanged.",
    ],
    outcome: "An evidence version is different from a document, PBC response, workpaper or review note; historical release evidence is preserved.",
    failure: "Stale/inadequate evidence cannot be newly linked; a reason is required for unlink.",
  },
  {
    id: "MOD-34", name: "Findings & Differences", route: "`findings`", component: "`FindingsView`",
    personas: "preparer → eligible decision-maker", scenario: "`audit-findings`",
    exists: "Scoped qualitative/monetary findings, sample promotion and correction decisions with signed/gross totals exist.", limits: "Complete reopen/waive/corrected/uncorrected and reporting/release re-evaluation matrices.",
    steps: [
      "Open Findings & Differences and inspect FND-01 or promote a sampled exception.",
      "Show immutable population/item/workpaper/evidence provenance.",
      "Create a qualitative finding without inventing a monetary amount, or enter a valid same-currency amount.",
      "Record a reasoned human disposition and compare gross absolute versus signed net values.",
      "Link a reviewed reflected journal when showing Corrected in TB; revisit release readiness and related reports.",
    ],
    outcome: "A finding disposition is not review-note clearance or an automatic immateriality/opinion decision.",
    failure: "Unresolved significant findings must independently block readiness; zero net does not make gross differences disappear.",
  },
  {
    id: "MOD-35", name: "Review Points", route: "`reviews`", component: "`ReviewDeskView`",
    personas: "reviewer → assigned responder → independent clearer", scenario: "`audit-findings`",
    exists: "Scoped cross-engagement queues, reassignment, exact-revision responses and independent clearance are reported verified.", limits: "Keep working behavior and rehearse one workpaper-target and one finding-target review.",
    steps: [
      "Open Review Desk, filter a permitted engagement and select RN-001/RN-002.",
      "Raise a point on an exact workpaper/finding revision; assign an eligible responder.",
      "Switch to that responder and attach a current response/evidence reference.",
      "Switch to a different eligible clearer and close the point.",
      "Revise the underlying subject and show a reopened point and required new response without changing finding disposition.",
    ],
    outcome: "Open, Responded, Cleared and Reopened states and all assignment reasons remain attributable.",
    failure: "Responder self-clearance, stale responses and ungranted sibling queues/exports are denied.",
  },
  {
    id: "MOD-36", name: "Reviews & Approvals", route: "`approvals`", component: "`ApprovalsEQRView`",
    personas: "manager → client management → partner → assigned independent EQR", scenario: "`full-practice`",
    exists: "Revision-bound management decisions, EQR assignment and current approval history are reported verified.", limits: "Preserve controls; provide a clear manual role-handoff explanation in the presentation.",
    steps: [
      "Open Sign-offs & EQR and inspect the current validated package/review requirements.",
      "Present the exact client-safe package to a granted management approver.",
      "Record management rationale/evidence as that person, distinct from staff approval.",
      "Assign an eligible independent EQR and demonstrate the separate concern/completion path when applicable.",
      "Change a source/package revision and show stale decisions requiring fresh human review.",
    ],
    outcome: "Approvals illustrate recorded human decisions only; the demo claims no legally binding signature and no professional certification.",
    failure: "A manager/partner already on the engagement team or same preparer must not become the independent EQR by role switching.",
  },
  {
    id: "MOD-37", name: "Completion & Release", route: "`delivery`", component: "`ReleaseCompletionView`",
    personas: "partner / permitted release actor", scenario: "`blocked-rework`",
    exists: "Readiness gates, exact artifact freeze/issue and amendment history are reported verified.", limits: "No replacement release engine; demonstrate blocking, resolution and exact local reissue.",
    steps: [
      "Open Release & Completion in Blocked / Rework State and inspect each blocker.",
      "Navigate to the owning screen for a missing review/input instead of forcing Ready.",
      "With the approved fixture, freeze the candidate and inspect exact artifact IDs and SHA-256s.",
      "Issue locally; read the visible no-external-delivery statement.",
      "Prepare an amendment, retain predecessor manifest and obtain fresh required decisions before reissue.",
    ],
    outcome: "A local release record is not an email, provider delivery, signature or live client report issuance.",
    failure: "Missing approvals, changed bytes, stale generation and duplicate same-generation issue must fail.",
  },
  {
    id: "MOD-38", name: "Records & Archive", route: "`records`", component: "`RecordsArchiveView`",
    personas: "records", scenario: "`full-practice`",
    exists: "Separate local archive copies, digest checks, successor lineage and hold/handover metadata are reported verified.", limits: "Preserve it; the presentation must explain local archive versus real retention clearly.",
    steps: [
      "Open Records & Archive for a released synthetic engagement.",
      "Archive the exact release artifacts and inspect copied IDs, sizes and digests.",
      "Review predecessor/successor records after an amended release.",
      "Apply a local hold and demonstrate blocked handover; lift it through the permitted manual action.",
      "Correct optional retention metadata with a reason and show the attributable history.",
    ],
    outcome: "IndexedDB copies and app metadata can be cleared by the browser owner; no Purview, server immutability or automatic disposal is promised.",
    failure: "A held handover or mismatched artifact must be rejected without a falsely successful archive record.",
  },
  {
    id: "MOD-39", name: "Administration", route: "`administration`", component: "`AdministrationView`",
    personas: "admin; professional functions remain with their granted actors", scenario: "`full-practice`",
    exists: "Firm settings and local identity/grant screens exist; prospective settings are the intended model.", limits: "Close consumption/version/collision/logo-unavailable cases and reconcile dedicated editor ownership.",
    steps: [
      "Open Firm Administration and review permitted firm/numbering/service defaults.",
      "Change one supported setting with a reason and inspect its revision.",
      "Create a new draft/preview to demonstrate that the new default applies prospectively.",
      "Open an already-issued invoice or released package and show that it is unchanged.",
      "Inspect user/grant settings separately; explain that system administration does not confer professional review powers.",
    ],
    outcome: "Settings have one owner and visible future effect, with no AI, tax/payroll, payment, Purview or automation controls.",
    failure: "Invalid numbering/defaults and excluded-feature toggles must not be accepted; settings cannot rewrite historic artifacts.",
  },
];
